-- ============================================================================
-- Seed catalog: 7 root categories, 3 sub-categories, 37 services
-- All inserts are idempotent (ON CONFLICT (slug) DO NOTHING).
-- Run once on a fresh DB or after the soft_delete_categories migration.
-- ============================================================================

-- ─── ROOT CATEGORIES ─────────────────────────────────────────────────────────
insert into public.categories
  (slug, parent_id, name_ar, name_en, description_ar, description_en, image_url, sort_order, is_visible)
values
  ('programming', null,
   'البرمجة والتطوير', 'Programming & Development',
   'حلول برمجية متكاملة تحوّل أفكارك إلى منتجات رقمية تعمل بكفاءة وأمان — من المواقع والتطبيقات إلى الأنظمة المخصصة وأدوات الأتمتة.',
   'End-to-end software solutions that turn your ideas into reliable, secure digital products — from websites and mobile apps to custom systems and automation tools.',
   'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=800&q=80',
   10, true),

  ('design', null,
   'التصميم', 'Design',
   'تصميم بصري يحكي قصة علامتك ويجذب جمهورك — من الهوية والشعار إلى واجهات المنتج والمحتوى البصري لمواقع التواصل.',
   'Visual design that tells your brand story and engages your audience — from identity and logo to product interfaces and social-ready visual content.',
   'https://images.unsplash.com/photo-1561070791-2526d30994b8?auto=format&fit=crop&w=800&q=80',
   20, true),

  ('hosting', null,
   'الاستضافة والبنية التحتية', 'Hosting & Infrastructure',
   'بنية تحتية موثوقة وآمنة لاستضافة موقعك أو تطبيقك — مراقبة على مدار الساعة، نسخ احتياطي تلقائي، وإدارة كاملة للخوادم والنطاقات.',
   'Reliable, secure infrastructure to host your site or app — 24/7 monitoring, automated backups, and full server and domain management.',
   'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=800&q=80',
   30, true),

  ('social-media', null,
   'السوشيال ميديا', 'Social Media',
   'إدارة احترافية لحضورك على منصات التواصل — محتوى مدروس، تفاعل حقيقي، وتقارير تكشف عائد كل جنيه أنفقته.',
   'Professional management of your social presence — thoughtful content, real engagement, and reports showing the ROI of every dollar spent.',
   'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?auto=format&fit=crop&w=800&q=80',
   40, true),

  ('digital-marketing', null,
   'التسويق الرقمي', 'Digital Marketing',
   'حملات مبنية على البيانات — SEO، إعلانات مدفوعة، بريد إلكتروني، وتحليل منافسين تجلب لك عملاء حقيقيين لا مجرد أرقام.',
   'Data-driven campaigns — SEO, paid ads, email, and competitor analysis that bring real customers, not just vanity metrics.',
   'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80',
   50, true),

  ('support-training', null,
   'الدعم الفني والتدريب', 'Support & Training',
   'دعم فني سريع وتدريب عملي على الأنظمة — لكي يستفيد فريقك من كل ميزة، ولا يتوقف عملك أبداً بسبب مشكلة تقنية.',
   'Fast technical support and hands-on system training — so your team uses every feature and a technical glitch never stops your work.',
   'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=800&q=80',
   60, true),

  ('testing-qa', null,
   'الاختبارات وضمان الجودة', 'Testing & QA',
   'نختبر منتجك قبل أن يختبره عملاؤك — اختبارات وظيفية، أداء، أمان، وتجربة استخدام تكشف العيوب قبل الإطلاق.',
   'We test your product before your customers do — functional, performance, security, and usability tests that catch issues before launch.',
   'https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=800&q=80',
   70, true)
on conflict (slug) do nothing;

-- ─── SUB-CATEGORIES (Testing only) ───────────────────────────────────────────
insert into public.categories
  (slug, parent_id, name_ar, name_en, description_ar, description_en, image_url, sort_order, is_visible)
values
  ('testing-functional',
   (select id from public.categories where slug = 'testing-qa'),
   'اختبارات وظيفية', 'Functional Testing',
   'نتأكد أن كل وظيفة تعمل كما هو متوقع — من زر التسجيل إلى دورة الدفع الكاملة، نختبر كل سيناريو يستخدمه عميلك.',
   'Verifying every function works as expected — from the signup button to the full checkout flow, every scenario your users will hit.',
   'https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=800&q=80',
   10, true),

  ('testing-non-functional',
   (select id from public.categories where slug = 'testing-qa'),
   'اختبارات غير وظيفية', 'Non-Functional Testing',
   'اختبار جودة التجربة — السرعة، الاستقرار تحت الضغط، التوافق مع كل الأجهزة، وسهولة الاستخدام.',
   'Quality-of-experience testing — speed, stability under load, cross-device compatibility, and overall usability.',
   'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80',
   20, true),

  ('testing-execution',
   (select id from public.categories where slug = 'testing-qa'),
   'طريقة التنفيذ', 'Execution Method',
   'تنفيذ يدوي (بعين بشرية للتفاصيل الدقيقة) أو آلي (آلاف الحالات في دقائق) — أيًّا كان الأنسب لمشروعك.',
   'Manual execution (human eye for nuance) or automated (thousands of cases in minutes) — whichever fits your project.',
   'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=800&q=80',
   30, true)
on conflict (slug) do nothing;

-- ─── SERVICES ────────────────────────────────────────────────────────────────
insert into public.services
  (category_id, slug, name_ar, name_en, short_description_ar, short_description_en,
   full_description_ar, full_description_en,
   estimated_price_min, estimated_price_max, currency, estimated_duration_days,
   cover_image, features_ar, features_en, deliverables_ar, deliverables_en,
   sort_order, is_visible, is_featured)
values

-- ═══ PROGRAMMING (7 services) ═══════════════════════════════════════════════

((select id from public.categories where slug = 'programming'),
 'web-development', 'برمجة وتطوير المواقع', 'Web Development',
 'مواقع احترافية من صفحة هبوط بسيطة إلى تطبيقات ويب متكاملة، Frontend و Backend بتقنيات حديثة.',
 'Professional websites from simple landing pages to full-stack web apps, built with modern stacks.',
 'نطوّر مواقع وتطبيقات ويب باستخدام Next.js و React في الواجهة، و Node.js مع PostgreSQL في الخلفية. كل مشروع يبدأ بفهم احتياجك، يمر بتصميم تجربة المستخدم، ثم التطوير والتسليم مع وثائق فنية كاملة. سواء كان موقعك تعريفياً، متجراً، أو تطبيقاً للحجوزات — نضمن أداءً سريعاً وتصميماً متجاوباً.',
 'We build web applications with Next.js + React on the frontend and Node.js + PostgreSQL on the backend. Each project starts with discovery, moves through UX design, then development and deploy-ready delivery with full technical docs. Whether brochure, store, or booking app — fast performance and responsive design guaranteed.',
 8000, 80000, 'EGP', 30,
 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=1200&q=80',
 array['تصميم متجاوب مع كل الأجهزة','تحسين SEO أساسي مدمج','لوحة تحكم محتوى (CMS)','دعم بعد التسليم لمدة 30 يومًا','كود نظيف وقابل للصيانة']::text[],
 array['Fully responsive on every device','Built-in basic SEO','Content management dashboard','30-day post-delivery support','Clean, maintainable code']::text[],
 array['موقع منشور على نطاقك','كود المصدر كاملاً','وثائق فنية للنشر والصيانة','تدريب على لوحة التحكم']::text[],
 array['Production-deployed site on your domain','Full source code','Technical docs for deployment','Admin-panel training session']::text[],
 10, true, true),

((select id from public.categories where slug = 'programming'),
 'mobile-development', 'برمجة تطبيقات الجوال', 'Mobile Apps',
 'تطبيقات iOS و Android بتقنية React Native — كود واحد، تجربة أصلية على المتجرين، نشر سريع.',
 'iOS and Android apps with React Native — one codebase, native UX on both stores, faster launch.',
 'نطوّر تطبيقات Mobile متعددة المنصات بتقنية React Native، مما يوفر 40-50% من تكلفة نسختين منفصلتين. التطبيق يستخدم مكونات أصلية فيبدو طبيعياً على كل نظام. نتولى النشر على App Store و Google Play، وندمج خدمات الإشعارات، المدفوعات، الخرائط، وتسجيل الدخول الاجتماعي.',
 'Cross-platform mobile apps with React Native, saving 40-50% versus two native builds. Native components mean each platform feels right. We handle App Store and Google Play submission plus integrations like push notifications, payments, maps, and social login.',
 25000, 150000, 'EGP', 60,
 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&w=1200&q=80',
 array['تطبيق على iOS و Android معاً','إشعارات Push فورية','تكامل مع بوابات الدفع','وضع غير متصل (Offline)','تحديثات OTA بدون مراجعة المتجر']::text[],
 array['Single project ships to iOS and Android','Real-time push notifications','Payment gateway integration','Offline mode','Over-the-air updates without store review']::text[],
 array['تطبيق منشور على المتجرين','كود المصدر بصلاحيات كاملة','حسابات على App Store و Google Play','دليل التحديث والإصدار']::text[],
 array['Published apps on both stores','Full source code ownership','App Store and Play Console accounts','Release and update playbook']::text[],
 20, true, true),

((select id from public.categories where slug = 'programming'),
 'ecommerce-development', 'تطوير المتاجر الإلكترونية', 'E-commerce Stores',
 'متجر إلكتروني كامل: سلة شراء، دفع، إدارة منتجات، شحن، وتقارير — جاهز لاستقبال أول طلب اليوم.',
 'Complete e-commerce: cart, checkout, product management, shipping, reports — ready for your first order today.',
 'متاجر إلكترونية مبنية على Shopify، WooCommerce، أو حلول مخصصة بـ Next.js. تشمل كتالوج بمتغيرات (لون/مقاس)، سلة، دفع آمن (PayMob، Stripe، تحويل بنكي)، حسابات عملاء، إدارة شحن، أكواد خصم، تقارير مبيعات، وتكامل مع المحاسبة والشحن المحلي.',
 'Online stores built on Shopify, WooCommerce, or custom Next.js. Includes catalog with variants, cart, secure checkout (PayMob, Stripe, bank transfer), customer accounts, shipping management, discount codes, sales reports, and integrations with accounting and local carriers.',
 15000, 100000, 'EGP', 45,
 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1200&q=80',
 array['كتالوج منتجات بمتغيرات','سلة شراء وحساب عميل','بوابات دفع محلية وعالمية','إدارة شحن وأكواد خصم','تقارير مبيعات وتحليلات']::text[],
 array['Product catalog with variants','Cart and customer accounts','Local plus international payment gateways','Shipping management and discount codes','Sales reports and analytics']::text[],
 array['متجر مفعّل ومنشور','تدريب على إدارة المنتجات والطلبات','تكامل وسائل الدفع والشحن','وثائق فنية للموظفين']::text[],
 array['Live, configured storefront','Product and order management training','Payment and shipping integrations','Staff documentation']::text[],
 30, true, true),

((select id from public.categories where slug = 'programming'),
 'cms-development', 'تطوير أنظمة إدارة المحتوى', 'Custom CMS',
 'نظام محتوى مخصص — صفحات، مقالات، صور، فيديو، وأقسام — قابل للإدارة بدون مبرمج.',
 'Custom content management — pages, posts, images, videos, sections — manageable without a developer.',
 'أنظمة محتوى تتيح لفريقك تحديث الموقع دون لمس كود. سواء كان Strapi، Sanity، WordPress، أو CMS مخصص — نختار الأنسب لحجم محتواك وعدد محرريه. كل نظام يشمل صلاحيات للأدوار، حفظ تلقائي للمسودات، معاينة قبل النشر، وسجل تغييرات كامل.',
 'CMSs that let your team update the site without touching code. Strapi, Sanity, WordPress, or a bespoke build — we pick what fits your content volume and editor count. Every system includes role permissions, draft auto-save, preview before publish, and a full change log.',
 12000, 60000, 'EGP', 25,
 'https://images.unsplash.com/photo-1542831371-29b0f74f9713?auto=format&fit=crop&w=1200&q=80',
 array['محرر مرئي للمحتوى (WYSIWYG)','صلاحيات لكل دور (محرر، مراجع، ناشر)','حفظ تلقائي ومعاينة قبل النشر','سجل تغييرات كامل','API للوصول من تطبيقات أخرى']::text[],
 array['Visual content editor (WYSIWYG)','Role-based permissions','Auto-save and pre-publish preview','Full change log','API for external apps']::text[],
 array['CMS منشور على خوادمك','حسابات للمحررين بصلاحياتها','تدريب وأدلة استخدام','دعم لمدة شهر بعد التسليم']::text[],
 array['Deployed CMS on your servers','Editor accounts with proper permissions','Training and user guides','30 days of post-launch support']::text[],
 40, true, false),

((select id from public.categories where slug = 'programming'),
 'bots-automation', 'برمجة الأدوات والبوتات', 'Bots and Automation',
 'بوتات WhatsApp، Telegram، Discord، وأدوات أتمتة توفر لفريقك ساعات من العمل اليدوي يومياً.',
 'WhatsApp, Telegram, and Discord bots plus automation tools that save hours of manual work daily.',
 'أتمتة العمليات المتكررة باستخدام بوتات ذكية وسكريبتات Python و Node.js. أمثلة: بوت WhatsApp يردّ على استفسارات العملاء مع تكامل CRM، بوت Telegram للتنبيهات، أداة تجمع البيانات من مصادر متعددة في Google Sheets، أو تكامل بين أنظمتك (نمط Zapier) لإنهاء العمل تلقائياً.',
 'Automate repetitive operations with smart bots and Python/Node.js scripts. Examples: a WhatsApp bot answering customer queries via CRM integration, a Telegram alerts bot, a scraper feeding Google Sheets from multiple sources, or Zapier-style integration between your systems.',
 5000, 40000, 'EGP', 15,
 'https://images.unsplash.com/photo-1531746790731-6c087fecd65a?auto=format&fit=crop&w=1200&q=80',
 array['بوتات WhatsApp و Telegram و Discord','تكامل مع CRM والـ APIs الخارجية','جدولة وتشغيل تلقائي (Cron)','تقارير دورية بالبريد','لوحة تحكم لرصد الأداء']::text[],
 array['WhatsApp, Telegram, Discord bots','CRM and external API integrations','Scheduled and cron automation','Periodic email reports','Monitoring dashboard']::text[],
 array['البوت أو الأداة جاهزة للعمل','وثائق التشغيل والصيانة','أرشيف الكود المصدري','تدريب لمشغل الأداة']::text[],
 array['Operational bot or tool','Operation and maintenance docs','Source code archive','Operator training']::text[],
 50, true, false),

((select id from public.categories where slug = 'programming'),
 'bi-dashboards', 'حلول ذكاء الأعمال ولوحات البيانات', 'BI and Dashboards',
 'لوحات بيانات تفاعلية تحوّل أرقام شركتك المتناثرة إلى قرارات واضحة في ثوانٍ.',
 'Interactive dashboards that turn scattered numbers into clear decisions in seconds.',
 'لوحات ذكاء أعمال تجمع البيانات من قاعدة بياناتك، Google Analytics، CRM، Excel، أو أي مصدر آخر، وتعرضها كرسوم بيانية ومؤشرات أداء تفاعلية. نستخدم Metabase، Looker Studio، أو لوحات مخصصة بـ Recharts. تشمل التصفية بالتاريخ، التصدير لـ Excel و PDF، وتنبيهات تلقائية.',
 'BI dashboards that pull from your database, Google Analytics, CRM, Excel, or any other source and render them as interactive charts and KPIs. Built on Metabase, Looker Studio, or custom Recharts. Includes date filtering, Excel/PDF export, and threshold-based alerts.',
 10000, 60000, 'EGP', 20,
 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
 array['دمج مصادر بيانات متعددة','رسوم بيانية تفاعلية وتصفية','مؤشرات أداء مع تنبيهات','تصدير لـ Excel و PDF','صلاحيات عرض حسب الدور']::text[],
 array['Unified view across data sources','Interactive charts and filtering','KPIs with smart alerts','Excel and PDF export','Role-based view permissions']::text[],
 array['لوحة بيانات منشورة','تكامل مع مصادر بياناتك','وثائق إضافة لوحات جديدة','تدريب لفريق القرار']::text[],
 array['Deployed dashboard','Source-system integrations','Docs for adding new dashboards','Training for decision makers']::text[],
 60, true, false),

((select id from public.categories where slug = 'programming'),
 'app-security', 'أمن وحماية التطبيقات', 'App Security',
 'حماية تطبيقك من الاختراقات: مراجعة أمنية، اختبار اختراق، إصلاح الثغرات، وتشفير البيانات الحساسة.',
 'Protect your app from breaches: security audit, penetration testing, vulnerability fixes, and sensitive-data encryption.',
 'مراجعة أمنية شاملة على ضوء OWASP Top 10: SQL Injection، XSS، CSRF، رفع ملفات غير آمن، صلاحيات معطّلة، ومشاكل المصادقة. نسلّم تقريراً مفصلاً بكل ثغرة وتأثيرها وخطوات الإصلاح. ثم نطبّق الإصلاحات (اختياري) ونعيد الاختبار للتأكد.',
 'End-to-end audit against OWASP Top 10: SQL Injection, XSS, CSRF, insecure upload, broken access control, and auth issues. You receive a detailed per-vulnerability report with impact and remediation steps. Optional remediation phase, followed by re-testing.',
 8000, 40000, 'EGP', 14,
 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&w=1200&q=80',
 array['مراجعة كاملة لقائمة OWASP Top 10','اختبار اختراق يدوي وآلي','تقرير مفصل بكل ثغرة وتأثيرها','إصلاح الثغرات (اختياري)','شهادة أمان بعد الإصلاح']::text[],
 array['Full OWASP Top 10 review','Manual and automated penetration testing','Detailed per-vulnerability report','Optional remediation phase','Security certificate post-fix']::text[],
 array['تقرير الأمان الشامل','خطة إصلاح بأولويات','إصلاح الثغرات الحرجة','إعادة اختبار بعد الإصلاح']::text[],
 array['Comprehensive security report','Prioritized remediation plan','Critical-vulnerability fixes','Post-fix re-test']::text[],
 70, true, false),

-- ═══ DESIGN (5 services) ═════════════════════════════════════════════════════

((select id from public.categories where slug = 'design'),
 'ux-prototyping', 'تجربة المستخدم والنماذج الأولية', 'UX and Prototyping',
 'نرسم رحلة المستخدم قبل أن نلمس البكسل — أبحاث، نماذج أولية تفاعلية، واختبار مع مستخدمين حقيقيين.',
 'We map the user journey before touching a pixel — research, interactive prototypes, and real-user testing.',
 'تبدأ خدمة تجربة المستخدم بفهم جمهورك وأهدافك التجارية. نُنتج خرائط رحلة المستخدم (user flows)، wireframes، ونماذج أولية تفاعلية في Figma يمكنك تجربتها كأنها تطبيق حقيقي قبل بدء التطوير. ثم نختبر النموذج مع 5-7 مستخدمين ونوثّق النتائج.',
 'UX work starts with understanding your audience and business goals. We deliver user-flow maps, wireframes, and clickable Figma prototypes you can experience like a real app before development. Then we test with 5-7 real users and document the findings.',
 6000, 25000, 'EGP', 15,
 'https://images.unsplash.com/photo-1559028012-481c04fa702d?auto=format&fit=crop&w=1200&q=80',
 array['أبحاث مستخدمين ومقابلات','user flows و wireframes','نموذج أولي تفاعلي في Figma','اختبار مع 5-7 مستخدمين','تقرير نتائج مفصل']::text[],
 array['User research and interviews','User flows and wireframes','Clickable Figma prototype','Usability test with 5-7 users','Detailed findings report']::text[],
 array['وثائق رحلة المستخدم','ملفات Figma مفتوحة','نموذج أولي قابل للمشاركة','تقرير اختبار المستخدمين']::text[],
 array['User journey documents','Editable Figma files','Shareable interactive prototype','User-testing report']::text[],
 10, true, false),

((select id from public.categories where slug = 'design'),
 'ui-design', 'تصميم واجهات المواقع والتطبيقات', 'UI Design',
 'واجهات حديثة جذابة، متجاوبة، وملتزمة بمعايير الوصول (Accessibility) — جاهزة للتطوير مباشرة.',
 'Modern, attractive, responsive interfaces meeting accessibility standards — ready for developer handoff.',
 'تصميم واجهات يبدأ بنظام تصميم (Design System) موحّد: ألوان، خطوط، أزرار، حقول، أيقونات. ثم نطبّق النظام على كل شاشات منتجك في Figma، نراعي حالات الفراغ والخطأ والتحميل، ونلتزم بمعايير WCAG للوصول. التسليم يشمل ملفات تطوير جاهزة (specs، assets، CSS variables).',
 'UI work starts with a unified design system: colors, typography, buttons, fields, icons. We then apply the system across every product screen in Figma, covering empty/error/loading states, and following WCAG accessibility standards. Handoff includes developer-ready specs, assets, and CSS variables.',
 8000, 35000, 'EGP', 18,
 'https://images.unsplash.com/photo-1545665277-5937489579f2?auto=format&fit=crop&w=1200&q=80',
 array['نظام تصميم موحّد (Design System)','كل شاشات المنتج بحالاتها المختلفة','التزام بمعايير الوصول WCAG','أيقونات وأصول جاهزة','ملف تطوير جاهز (specs و assets)']::text[],
 array['Unified design system','All product screens with every state','WCAG-compliant accessibility','Icons and ready assets','Developer-ready specs and assets']::text[],
 array['ملف Figma كامل','مكتبة نظام التصميم','حزمة أيقونات وأصول','وثائق التسليم للمطور']::text[],
 array['Complete Figma file','Design-system library','Icon and asset package','Developer handoff documentation']::text[],
 20, true, true),

((select id from public.categories where slug = 'design'),
 'brand-identity', 'تصميم الهوية البصرية', 'Brand Identity',
 'هوية كاملة: شعار، ألوان، خطوط، أيقونات، وأنماط استخدام — كل ما تحتاجه ليتذكرك جمهورك.',
 'Full identity: logo, colors, typography, icons, and usage guidelines — everything to make your brand memorable.',
 'بناء هوية بصرية متكاملة لعلامتك التجارية. نبدأ بورشة استكشاف لفهم شخصية الماركة وجمهورها، ثم نقترح 3 اتجاهات للشعار، نختار الأنسب ونطوّره بدقة. الناتج هو دليل هوية (Brand Book) يحوي الشعار بكل صيغه، نظام الألوان، الخطوط، الأيقونات، والقواعد البصرية لاستخدامها على كل المنصات.',
 'A complete visual identity for your brand. We start with a discovery workshop to understand brand personality and audience, then propose 3 logo directions, refine the best one, and deliver a Brand Book covering logo in all variants, color system, typography, icons, and visual rules for every platform.',
 10000, 50000, 'EGP', 21,
 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?auto=format&fit=crop&w=1200&q=80',
 array['ورشة استكشاف للماركة','3 اتجاهات شعار للاختيار','نظام ألوان وخطوط','حزمة أيقونات أساسية','دليل هوية (Brand Book) كامل']::text[],
 array['Brand discovery workshop','3 logo directions to choose from','Color and typography system','Core icon set','Comprehensive Brand Book']::text[],
 array['الشعار بكل الصيغ والملفات','دليل الهوية البصرية PDF','حزمة الأيقونات والأصول','قوالب بطاقات وأوراق رسمية']::text[],
 array['Logo in every format','Brand Identity Guidelines PDF','Icon and asset pack','Business-card and letterhead templates']::text[],
 30, true, true),

((select id from public.categories where slug = 'design'),
 'social-media-design', 'تصميم منشورات السوشيال ميديا', 'Social Media Posts',
 'بوستات وستوريز وريلز جاهزة للنشر — حزم شهرية تحافظ على هويتك البصرية على كل المنصات.',
 'Posts, stories, and reels ready to publish — monthly bundles that keep visual identity consistent across platforms.',
 'حزم شهرية من المنشورات البصرية لمواقع التواصل — تصميمات Instagram و Facebook و LinkedIn و TikTok مع مراعاة المقاسات المختلفة (Feed، Story، Reels). نقترح خطة محتوى شهرية مرتبطة بمناسبات وحملاتك، ونصمم القوالب بحيث يكون التحديث الأسبوعي بسيطاً.',
 'Monthly social-design bundles — Instagram, Facebook, LinkedIn, TikTok with all required sizes (Feed, Story, Reels). We propose a monthly content plan tied to events and your campaigns, and build templates so weekly updates stay simple.',
 4000, 18000, 'EGP', 15,
 'https://images.unsplash.com/photo-1611605698335-8b1569810432?auto=format&fit=crop&w=1200&q=80',
 array['تصاميم لـ Instagram و Facebook و TikTok','مقاسات Feed و Story و Reels','خطة محتوى شهرية مقترحة','قوالب قابلة للتحديث الأسبوعي','مونتاج Reels و Shorts قصير']::text[],
 array['Designs for Instagram, Facebook, TikTok','Feed, Story, and Reels sizes','Suggested monthly content plan','Reusable weekly templates','Short Reels and Shorts editing']::text[],
 array['حزمة 20-30 تصميم شهرياً','قوالب قابلة للتعديل','مونتاج فيديو قصير','ملفات مفتوحة لتعديلاتك المستقبلية']::text[],
 array['20-30 designs per month','Editable templates','Short video editing','Open source files for future tweaks']::text[],
 40, true, false),

((select id from public.categories where slug = 'design'),
 'print-design', 'تصميم الإعلانات المطبوعة واليافطات', 'Print and Banner Design',
 'تصميم لافتات شوارع، بروشورات، رول-آب، أوراق رسمية — بجودة طباعة عالية وملفات جاهزة للمطبعة.',
 'Street banners, brochures, roll-ups, letterheads — high print-quality designs with press-ready files.',
 'تصميم مطبوعات احترافية بدقة طباعة 300 DPI، ألوان CMYK، وحوافّ Bleed جاهزة للمطبعة. نغطي كل المطبوعات: لافتات الشوارع، بروشورات A4/DL، رول-آب 80×200، بروشورات Z-Fold، بطاقات أعمال، أوراق رسمية، وقوائم طعام للمطاعم. التسليم بصيغ PDF/X-1a، AI، PSD.',
 'Professional print design at 300 DPI, CMYK colors, with bleed — press-ready. We cover every format: street banners, A4/DL brochures, 80×200 roll-ups, Z-Fold brochures, business cards, letterheads, and restaurant menus. Delivered as PDF/X-1a, AI, PSD.',
 2500, 15000, 'EGP', 10,
 'https://images.unsplash.com/photo-1531973576160-7125cd663d86?auto=format&fit=crop&w=1200&q=80',
 array['دقة طباعة 300 DPI و CMYK','حوافّ Bleed جاهزة','تصميم متعدد الصيغ والمقاسات','مراجعتان مجانيتان','تنسيق مع المطبعة (إن طلبت)']::text[],
 array['300 DPI and CMYK print specs','Press-ready bleeds','Multi-format design','Two rounds of revisions included','Press coordination if requested']::text[],
 array['ملفات PDF/X-1a للمطبعة','ملفات مفتوحة AI و PSD','معاينة مرئية قبل الطباعة','نصائح اختيار الورق والمطبعة']::text[],
 array['PDF/X-1a press files','Open AI and PSD files','Visual preview before print','Paper and printshop recommendations']::text[],
 50, true, false),

-- ═══ HOSTING (4 services) ════════════════════════════════════════════════════

((select id from public.categories where slug = 'hosting'),
 'shared-vps-hosting', 'استضافة مشتركة و VPS', 'Shared and VPS Hosting',
 'استضافة موثوقة بأسعار مناسبة — مساحة كافية، نطاق فرعي مجاني، SSL، ولوحة تحكم cPanel.',
 'Reliable hosting at sensible prices — generous storage, free subdomain, SSL, and a cPanel dashboard.',
 'استضافة مشتركة لمواقع صغيرة ومتوسطة، أو VPS مخصص بصلاحيات كاملة. كل خطة تشمل SSL مجاني، نطاقاً فرعياً، نسخ احتياطي أسبوعي، وحماية DDoS أساسية. الخوادم في مراكز بيانات أوروبية وعربية بأقل زمن استجابة لجمهورك.',
 'Shared hosting for small/medium sites or a fully-controlled VPS. Every plan includes free SSL, a subdomain, weekly backups, and basic DDoS protection. Data centers in Europe and the Middle East for minimum latency to your audience.',
 1200, 12000, 'EGP', 3,
 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=80',
 array['مساحة تخزين مرنة','SSL مجاني تلقائي','نسخ احتياطي أسبوعي','حماية DDoS أساسية','لوحة تحكم cPanel']::text[],
 array['Flexible storage','Free auto-SSL','Weekly backups','Basic DDoS protection','cPanel dashboard']::text[],
 array['حساب استضافة مفعّل','SSL مثبت','تكامل مع نطاقك','تدريب على cPanel']::text[],
 array['Active hosting account','Installed SSL','Domain wiring','cPanel walkthrough']::text[],
 10, true, false),

((select id from public.categories where slug = 'hosting'),
 'dedicated-cloud-servers', 'خوادم سحابية مخصصة', 'Dedicated Cloud Servers',
 'إعداد وإدارة خوادم AWS، DigitalOcean، Hetzner — تخصيص حسب الحمل، نسخ احتياطي، ومراقبة مستمرة.',
 'AWS, DigitalOcean, Hetzner setup and management — sized to your load, backups, and active monitoring.',
 'إعداد وإدارة خوادم سحابية على AWS (EC2, RDS, S3, CloudFront)، DigitalOcean، Hetzner، أو Azure. نختار الحجم المناسب لحملك، نعدّ Auto-Scaling، CDN، نسخاً احتياطياً يومياً، ومراقبة 24/7 مع تنبيهات Slack أو واتس آب. نتعامل مع تحديثات الأمان الدورية ودوال الطوارئ.',
 'Setup and management of AWS (EC2, RDS, S3, CloudFront), DigitalOcean, Hetzner, or Azure. We size for your load, configure auto-scaling, CDN, daily backups, and 24/7 monitoring with Slack/WhatsApp alerts. We handle security patching and emergency response.',
 5000, 50000, 'EGP', 7,
 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80',
 array['إعداد كامل لـ AWS / DigitalOcean / Hetzner','Auto-Scaling حسب الحمل','نسخ احتياطي يومي إلى مكان منفصل','مراقبة 24/7 مع تنبيهات فورية','تحديثات أمنية دورية']::text[],
 array['Full AWS / DigitalOcean / Hetzner setup','Load-based auto-scaling','Daily off-site backups','24/7 monitoring with real-time alerts','Regular security patching']::text[],
 array['خادم منشور ومُؤمَّن','وثائق البنية التحتية','وصول كامل للحساب','عقد إدارة شهري (اختياري)']::text[],
 array['Hardened, deployed server','Infrastructure documentation','Full account ownership','Optional monthly management contract']::text[],
 20, true, true),

((select id from public.categories where slug = 'hosting'),
 'domains-email', 'إدارة النطاقات وبريد العمل', 'Domains and Business Email',
 'حجز نطاقك، ضبط DNS، إعداد بريد عمل احترافي مع تكامل Outlook و Gmail.',
 'Domain registration, DNS configuration, professional business email integrated with Outlook and Gmail.',
 'إدارة دورة حياة نطاقاتك من البحث والحجز إلى التجديد. نضبط سجلات DNS (A, MX, TXT, SPF, DKIM, DMARC) لتحسين توصيل البريد ومنع التزوير. نُعدّ بريد عمل احترافياً (info@yourbrand.com) عبر Google Workspace أو Microsoft 365 أو Zoho Mail مع تكامل سلس مع Outlook و Gmail.',
 'Full domain lifecycle management from search and registration to renewal. We configure DNS records (A, MX, TXT, SPF, DKIM, DMARC) for deliverability and anti-spoofing. We set up professional business email via Google Workspace, Microsoft 365, or Zoho Mail with seamless Outlook and Gmail integration.',
 1500, 10000, 'EGP', 5,
 'https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?auto=format&fit=crop&w=1200&q=80',
 array['حجز ونقل النطاقات','ضبط DNS متقدم','بريد عمل احترافي (Google/M365/Zoho)','SPF + DKIM + DMARC لتوصيل أفضل','تكامل Outlook و Gmail']::text[],
 array['Domain registration and transfer','Advanced DNS configuration','Professional business email','SPF, DKIM, DMARC for deliverability','Outlook and Gmail integration']::text[],
 array['نطاق مفعّل ومُؤمَّن','حسابات بريد للموظفين','وثائق إعدادات DNS','دليل إعداد عملاء البريد']::text[],
 array['Active, secured domain','Staff email accounts','DNS configuration docs','Mail-client setup guide']::text[],
 30, true, false),

((select id from public.categories where slug = 'hosting'),
 'server-monitoring', 'مراقبة وصيانة الخوادم', 'Server Monitoring and Maintenance',
 'مراقبة على مدار الساعة، تنبيهات قبل الأعطال، تحديثات أمنية، ونسخ احتياطي تلقائي يومي.',
 'Around-the-clock monitoring, pre-failure alerts, security patches, and daily automated backups.',
 'عقد إدارة شهري للخوادم: نراقب CPU، الذاكرة، القرص، الشبكة، وزمن استجابة التطبيق على مدار الساعة. ننبّه فريقك قبل تجاوز العتبات الحرجة. نطبّق التحديثات الأمنية الشهرية، نتحقق من النسخ الاحتياطي يومياً، ونستجيب لطوارئ خلال 30 دقيقة.',
 'Monthly server management: 24/7 monitoring of CPU, memory, disk, network, and app latency. We alert before critical thresholds are crossed. Monthly security patching, daily backup verification, and 30-minute emergency response.',
 2500, 15000, 'EGP', 30,
 'https://images.unsplash.com/photo-1581090464777-f3220bbe1b8b?auto=format&fit=crop&w=1200&q=80',
 array['مراقبة 24/7 مع لوحة بيانات حية','تنبيهات قبل الأعطال (Slack/WhatsApp/Email)','تحديثات أمنية شهرية','تحقق يومي من النسخ الاحتياطي','استجابة طوارئ خلال 30 دقيقة']::text[],
 array['24/7 monitoring with live dashboard','Pre-failure alerts (Slack/WhatsApp/Email)','Monthly security patching','Daily backup verification','30-minute emergency response']::text[],
 array['لوحة مراقبة حية','تقارير صحة الخادم شهرياً','سجل التحديثات والإصلاحات','رقم طوارئ مباشر']::text[],
 array['Live monitoring dashboard','Monthly server health reports','Patch and fix log','Direct emergency contact']::text[],
 40, true, false),

-- ═══ SOCIAL MEDIA (5 services) ═══════════════════════════════════════════════

((select id from public.categories where slug = 'social-media'),
 'social-management', 'إدارة الحسابات والنشر', 'Account Management',
 'إدارة كاملة لحساباتك على Instagram، Facebook، Twitter، LinkedIn — تخطيط شهري، نشر، وردود على المتابعين.',
 'Full management of Instagram, Facebook, Twitter, LinkedIn — monthly planning, publishing, and reply handling.',
 'إدارة شاملة لحضورك على السوشيال ميديا: خطة محتوى شهرية مرتبطة بأهدافك التجارية، 15-20 منشوراً متنوعاً (صور، فيديو، Reels، Stories)، نشر بمواعيد محسوبة، وردود على تعليقات ورسائل الجمهور خلال ساعات قليلة. تقرير شهري واضح بالنتائج والتوصيات.',
 'Comprehensive social management: monthly content plan tied to business goals, 15-20 varied posts (image, video, Reels, Stories), publishing at optimized times, and replies to comments and DMs within hours. Clear monthly report with results and recommendations.',
 5000, 25000, 'EGP', 30,
 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?auto=format&fit=crop&w=1200&q=80',
 array['خطة محتوى شهرية','15-20 منشور متنوع شهرياً','نشر بمواعيد محسوبة','ردود على التعليقات والرسائل','تقرير أداء شهري']::text[],
 array['Monthly content plan','15-20 varied posts per month','Posts scheduled at peak times','Comment and DM responses','Monthly performance report']::text[],
 array['تقويم محتوى شهري','منشورات منشورة على كل المنصات','تقرير الأداء الشهري','اجتماع مراجعة شهري']::text[],
 array['Monthly content calendar','Posts published across platforms','Monthly performance report','Monthly review meeting']::text[],
 10, true, true),

((select id from public.categories where slug = 'social-media'),
 'content-creation', 'إنشاء محتوى مرئي مختص', 'Visual Content Creation',
 'تصوير، مونتاج فيديو، Reels و Shorts، وصور احترافية — محتوى يجعل صفحاتك تنافس الكبار.',
 'Shooting, video editing, Reels and Shorts, professional photography — content that punches above its weight.',
 'باقات إنتاج محتوى مرئي بمقاييس استوديو: تصوير منتجاتك بإضاءة احترافية، مونتاج فيديوهات Reels قصيرة بإيقاع سريع وموسيقى ترند، وصور لوكيشن أو في موقع عملك. نأتي بفريق التصوير والإضاءة، ونسلّمك المحتوى منسّقاً ومعدّلاً وجاهزاً للنشر.',
 'Studio-grade visual content: professional product photography with proper lighting, fast-paced Reels editing with trending audio, and on-location or workplace shoots. We bring the crew and lighting and deliver finished, color-graded content ready to publish.',
 6000, 35000, 'EGP', 14,
 'https://images.unsplash.com/photo-1493612276216-ee3925520721?auto=format&fit=crop&w=1200&q=80',
 array['تصوير احترافي بمعدات استوديو','مونتاج Reels و Shorts','صور منتجات وبورتريه','معالجة لون وصوت','تسليم بصيغ متعددة (Feed/Story/Reel)']::text[],
 array['Studio-grade photography','Reels and Shorts editing','Product and portrait shoots','Color and audio grading','Multi-format delivery (Feed/Story/Reel)']::text[],
 array['حزمة محتوى مرئي شهرية','صور منسقة بدقة عالية','فيديوهات قصيرة منشورة','ملفات مفتوحة (Raw + Edits)']::text[],
 array['Monthly visual content pack','High-res, retouched photos','Published short videos','Open files (Raw plus Edits)']::text[],
 20, true, false),

((select id from public.categories where slug = 'social-media'),
 'paid-ads', 'الإعلانات المدفوعة', 'Paid Ads',
 'حملات مدفوعة على Meta، TikTok، LinkedIn — استهداف دقيق، إبداعات متعددة، وتقارير بعائد كل جنيه.',
 'Paid campaigns on Meta, TikTok, LinkedIn — precise targeting, multiple creatives, ROI per dollar reporting.',
 'إدارة كاملة لحملاتك المدفوعة على Meta Ads، TikTok Ads، Google Ads، و LinkedIn Ads. نبدأ بأبحاث الجمهور والمنافسين، ثم نختبر 3-5 إبداعات في كل حملة لاكتشاف الأنجح. نُحسّن الحملة كل أسبوع ونرسل لك تقريراً واضحاً بعدد العملاء المحتملين، التكلفة، وعائد الاستثمار.',
 'End-to-end paid-campaign management on Meta, TikTok, Google, and LinkedIn Ads. We start with audience and competitor research, then split-test 3-5 creatives per campaign to find the winner. Weekly optimization and clear weekly reports on leads, cost per lead, and ROI.',
 6000, 30000, 'EGP', 30,
 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80',
 array['Meta و TikTok و Google و LinkedIn','اختبار 3-5 إبداعات لكل حملة','تحسين أسبوعي مستمر','تتبع التحويلات (Pixel و Conversion API)','تقرير ROI أسبوعي']::text[],
 array['Meta, TikTok, Google, LinkedIn','3-5 creatives split-tested per campaign','Weekly optimization','Conversion tracking (Pixel and Conversion API)','Weekly ROI reports']::text[],
 array['حسابات إعلانية مُعدّة','حملات نشطة محسّنة','تقارير ROI أسبوعية','اجتماع مراجعة شهري']::text[],
 array['Configured ad accounts','Live, optimized campaigns','Weekly ROI reports','Monthly review meeting']::text[],
 30, true, true),

((select id from public.categories where slug = 'social-media'),
 'social-analytics', 'تحليل الأداء والتقارير', 'Performance Analytics',
 'تقارير شهرية واضحة بمؤشرات الأداء، أفضل المنشورات، ومقترحات لتحسين الشهر التالي.',
 'Clear monthly reports with KPIs, top-performing posts, and recommendations for next month.',
 'تقارير شهرية احترافية بـ PDF تجمع بيانات Instagram Insights، Facebook Business، TikTok Analytics، LinkedIn Page، و Google Analytics في صورة واحدة. تشمل: نمو المتابعين، الوصول والتفاعل، أفضل 5 منشورات، أوقات الذروة، مقارنة بالمنافسين، وتوصيات قابلة للتنفيذ للشهر التالي.',
 'Professional monthly PDF reports that consolidate Instagram Insights, Facebook Business, TikTok Analytics, LinkedIn Page, and Google Analytics into a single view. Includes follower growth, reach and engagement, top 5 posts, peak times, competitor benchmarks, and actionable next-month recommendations.',
 3000, 12000, 'EGP', 30,
 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
 array['تقرير PDF شهري احترافي','جمع بيانات من كل المنصات','مقارنة بالمنافسين','أفضل 5 منشورات وأوقات الذروة','توصيات قابلة للتنفيذ']::text[],
 array['Professional monthly PDF report','Aggregated data from all platforms','Competitor benchmarks','Top 5 posts and peak times','Actionable recommendations']::text[],
 array['تقرير PDF شهري','جلسة مراجعة 60 دقيقة','خطة عمل للشهر التالي','لوحة بيانات مباشرة (اختياري)']::text[],
 array['Monthly PDF report','60-minute review session','Next-month action plan','Optional live dashboard']::text[],
 40, true, false),

((select id from public.categories where slug = 'social-media'),
 'brand-reputation', 'إدارة سمعة العلامة التجارية', 'Brand Reputation',
 'مراقبة ذكر علامتك على كل المنصات، الرد على المراجعات، وإدارة الأزمات قبل أن تتفاقم.',
 'Monitor brand mentions everywhere, reply to reviews, and manage crises before they escalate.',
 'حماية سمعتك على الإنترنت بمراقبة دائمة لذكر اسم علامتك على Google Reviews، Trustpilot، السوشيال ميديا، والمنتديات. نردّ على المراجعات السلبية باحترافية، نعزز الإيجابية، وندير الأزمات (Crisis Management) بخطة جاهزة. تنبيهات فورية لو ظهر تهديد لسمعتك.',
 'Online reputation protection with constant monitoring of brand mentions on Google Reviews, Trustpilot, social media, and forums. Professional replies to negative reviews, amplification of positive ones, and crisis management with a prepared playbook. Instant alerts when reputation threats appear.',
 4000, 18000, 'EGP', 30,
 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=1200&q=80',
 array['مراقبة 24/7 لذكر علامتك','الرد على Google Reviews و Trustpilot','تنبيهات فورية لأي تهديد','خطة إدارة الأزمات الجاهزة','تعزيز المراجعات الإيجابية']::text[],
 array['24/7 brand mention monitoring','Replies to Google Reviews and Trustpilot','Real-time threat alerts','Crisis management playbook','Positive review amplification']::text[],
 array['لوحة مراقبة سمعة مباشرة','ردود احترافية على المراجعات','خطة استجابة للأزمات','تقرير تحليل سمعة شهري']::text[],
 array['Live reputation dashboard','Professional review replies','Crisis-response plan','Monthly reputation analysis report']::text[],
 50, true, false),

-- ═══ DIGITAL MARKETING (4 services) ══════════════════════════════════════════

((select id from public.categories where slug = 'digital-marketing'),
 'seo', 'تحسين محركات البحث (SEO)', 'Search Engine Optimization',
 'تظهر في النتائج الأولى لأهم كلمات جمهورك — تحليل، تحسين تقني، محتوى، وبناء روابط.',
 'Rank #1 for your audience key terms — audit, technical SEO, content, and link building.',
 'برنامج SEO متكامل من 3 مراحل: مراجعة تقنية شاملة (سرعة، structured data، sitemaps، robots، canonical، indexing)، تحسين on-page لكل صفحة (meta، schema، روابط داخلية، محتوى مقصود)، وبناء روابط خارجية عبر مقالات ضيف ومراجعات في مواقع موثوقة. تقرير ترتيب شهري لـ 30-50 كلمة مفتاحية.',
 'A 3-phase SEO program: complete technical audit (speed, structured data, sitemaps, robots, canonical, indexing), on-page optimization for every page (meta, schema, internal linking, intent-matching content), and off-page link building via guest posts and reviews on authority sites. Monthly ranking report for 30-50 target keywords.',
 8000, 35000, 'EGP', 90,
 'https://images.unsplash.com/photo-1599658880436-c61792e70672?auto=format&fit=crop&w=1200&q=80',
 array['مراجعة تقنية شاملة','تحسين on-page لكل صفحة','بناء روابط خارجية','تتبع 30-50 كلمة مفتاحية','تقرير ترتيب شهري']::text[],
 array['Comprehensive technical audit','Per-page on-page optimization','Off-page link building','Tracking 30-50 keywords','Monthly ranking report']::text[],
 array['تقرير المراجعة التقنية','خطة SEO ربع سنوية','تقارير الترتيب الشهرية','اجتماع مراجعة كل شهرين']::text[],
 array['Technical audit report','Quarterly SEO roadmap','Monthly ranking reports','Bi-monthly review meeting']::text[],
 10, true, true),

((select id from public.categories where slug = 'digital-marketing'),
 'email-automation', 'التسويق بالبريد والأتمتة', 'Email and Automation',
 'حملات بريد إلكتروني مدروسة + سيناريوهات أتمتة تحوّل المشتركين إلى عملاء بدون تدخل يومي.',
 'Smart email campaigns + automation flows that convert subscribers into customers hands-off.',
 'إعداد بنية البريد التسويقي على Mailchimp، Klaviyo، Brevo، أو ActiveCampaign. تصميم 5-7 سيناريوهات أتمتة جاهزة (ترحيب، سلة متروكة، استرجاع عميل، يوم ميلاد، ما بعد الشراء). تصميم وكتابة 4 نشرات شهرية، وتحسين معدل الفتح والنقر بالاختبار المستمر.',
 'Marketing-email setup on Mailchimp, Klaviyo, Brevo, or ActiveCampaign. Design of 5-7 automation flows (welcome, cart abandonment, win-back, birthday, post-purchase). Design and copy for 4 monthly newsletters, and continuous open/click-rate optimization via testing.',
 5000, 22000, 'EGP', 30,
 'https://images.unsplash.com/photo-1596526131083-e8c633c948d2?auto=format&fit=crop&w=1200&q=80',
 array['Mailchimp / Klaviyo / Brevo / ActiveCampaign','5-7 سيناريوهات أتمتة جاهزة','4 نشرات شهرية بتصميم احترافي','اختبارات A/B لتحسين الفتح','تقارير أداء أسبوعية']::text[],
 array['Mailchimp / Klaviyo / Brevo / ActiveCampaign','5-7 ready automation flows','4 designed monthly newsletters','A/B testing for open rates','Weekly performance reports']::text[],
 array['حساب بريد مُعدّ وجاهز','مكتبة قوالب بريدية','سيناريوهات أتمتة نشطة','تقارير أداء أسبوعية']::text[],
 array['Configured email account','Template library','Live automation flows','Weekly performance reports']::text[],
 20, true, false),

((select id from public.categories where slug = 'digital-marketing'),
 'integrated-campaigns', 'إدارة الحملات المتكاملة', 'Integrated Campaigns',
 'حملات متعددة القنوات (Google + Meta + Email) — رسالة موحدة، تتبع كامل، وعائد قابل للقياس.',
 'Multi-channel campaigns (Google + Meta + Email) — unified message, full attribution, measurable ROI.',
 'تنفيذ حملات تسويقية موسمية متكاملة: تحدد هدفاً واضحاً (إطلاق منتج، عرض موسمي، توعية بعلامة)، نصمم رسالة موحدة، ثم ننفّذها عبر 3-5 قنوات (Google Ads، Meta، TikTok، Email، Influencers). نتبع كل تفاعل من النقرة الأولى للشراء، ونحسب عائد كل قناة.',
 'End-to-end seasonal campaigns: define a clear goal (product launch, seasonal offer, brand awareness), craft a unified message, then deploy across 3-5 channels (Google Ads, Meta, TikTok, Email, Influencers). We attribute every touchpoint from first click to purchase and compute per-channel ROI.',
 12000, 60000, 'EGP', 45,
 'https://images.unsplash.com/photo-1432888622747-4eb9a8efeb07?auto=format&fit=crop&w=1200&q=80',
 array['حملة موحدة على 3-5 قنوات','رسالة وإبداعات متناغمة','تتبع كامل من النقرة للشراء','عائد كل قناة بوضوح','تحسين أسبوعي مستمر']::text[],
 array['Unified campaign across 3-5 channels','Cohesive message and creatives','Full first-click to purchase attribution','Clear per-channel ROI','Weekly optimization']::text[],
 array['خطة حملة موثقة','إبداعات لكل قناة','لوحة بيانات حملة موحدة','تقرير ختامي بعائد كل قناة']::text[],
 array['Documented campaign plan','Per-channel creatives','Unified campaign dashboard','Final report with per-channel ROI']::text[],
 30, true, false),

((select id from public.categories where slug = 'digital-marketing'),
 'competitor-keyword-analysis', 'تحليل المنافسين والكلمات المفتاحية', 'Competitor and Keyword Analysis',
 'نكشف لك ماذا يفعل منافسوك، أين يستثمرون، وأي الكلمات تحوّل لهم زواراً — فتسبقهم بمعرفة.',
 'Reveal what competitors do, where they invest, and which keywords convert — so you outpace them with knowledge.',
 'تحليل تنافسي شامل لـ 5-10 منافسين: استراتيجيتهم على السوشيال، إعلاناتهم النشطة (Meta Ad Library)، ترتيبهم في Google لأهم الكلمات، روابطهم الخلفية، وميزانية SEO المقدّرة. نسلّمك خريطة الفرص: ماذا يفعلونه ولا تفعله، وأين تكلفة الحصول على العميل أرخص.',
 'Comprehensive competitive analysis of 5-10 competitors: social strategy, active ads (Meta Ad Library), Google ranking for key terms, backlinks, and estimated SEO budget. You receive an opportunity map: what they do that you do not, and where customer acquisition is cheaper.',
 5000, 20000, 'EGP', 14,
 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&w=1200&q=80',
 array['تحليل 5-10 منافسين','استراتيجيتهم على كل القنوات','إعلاناتهم النشطة وميزانيتهم المقدّرة','الكلمات التي يحققون منها زيارات','خريطة الفرص لتمييزك']::text[],
 array['Analysis of 5-10 competitors','Their strategy across every channel','Active ads and estimated budgets','Keywords driving their traffic','Opportunity map for differentiation']::text[],
 array['تقرير تحليل تنافسي مفصل','قائمة 50+ كلمة مفتاحية ذهبية','خريطة فرص قابلة للتنفيذ','جلسة عرض ومناقشة 90 دقيقة']::text[],
 array['Detailed competitive analysis report','List of 50+ high-opportunity keywords','Actionable opportunity map','90-minute presentation session']::text[],
 40, true, false),

-- ═══ SUPPORT and TRAINING (4 services) ═══════════════════════════════════════

((select id from public.categories where slug = 'support-training'),
 'multi-channel-support', 'دعم فني متعدد القنوات', 'Multi-Channel Tech Support',
 'دعم فني عبر الدردشة، التذاكر، والهاتف — أوقات استجابة محددة بعقد، وتقارير شهرية.',
 'Tech support via chat, tickets, and phone — SLA-bound response times and monthly reports.',
 'فريق دعم فني محترف يتعامل مع عملائك بالعربية أو الإنجليزية. نوفر قنوات متعددة: دردشة مباشرة على موقعك، نظام تذاكر، رد على البريد، وهاتف داخلي مخصص. اتفاقية مستوى خدمة (SLA) واضحة: وقت الاستجابة الأول 15 دقيقة في ساعات العمل، 2 ساعة خارجها. تقرير أداء شهري مفصل.',
 'A professional support team handling your customers in Arabic or English. Multi-channel: live chat on your site, ticketing system, email replies, and a dedicated phone line. Clear SLA: first response in 15 minutes during business hours, 2 hours outside. Detailed monthly performance report.',
 8000, 35000, 'EGP', 30,
 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=1200&q=80',
 array['دردشة + تذاكر + بريد + هاتف','SLA: استجابة خلال 15 دقيقة','دعم بالعربية والإنجليزية','تقرير أداء شهري','قاعدة معرفة ذاتية للعملاء']::text[],
 array['Chat + tickets + email + phone','SLA: 15-minute first response','Arabic and English support','Monthly performance report','Self-service knowledge base']::text[],
 array['نظام دعم منشور ومتكامل','فريق متاح حسب SLA','قاعدة معرفة على موقعك','تقارير شهرية وجلسة مراجعة']::text[],
 array['Deployed support stack','SLA-bound team','Knowledge base on your site','Monthly reports and review session']::text[],
 10, true, false),

((select id from public.categories where slug = 'support-training'),
 'system-training', 'تدريب على استخدام الأنظمة', 'System Training',
 'ورش تدريب عملية — أونلاين أو حضوريًا — على لوحات التحكم، تطبيقات إدارة، وأدوات داخلية.',
 'Hands-on training workshops — online or onsite — on admin panels, management apps, and internal tools.',
 'برامج تدريب مخصصة لفريقك على الأنظمة التي يستخدمها يومياً: لوحات تحكم WordPress أو Shopify، CRM، أنظمة المخزون، أدوات Office 365 و Google Workspace، أو منتجاتك الداخلية. ورش 2-8 ساعات بمواد تدريبية مكتوبة وفيديوهات. اختبار قبول في نهاية كل ورشة.',
 'Custom training programs for the tools your team uses daily: WordPress or Shopify admin panels, CRM, inventory systems, Office 365 and Google Workspace, or your internal products. 2-8 hour workshops with written materials and videos. Acceptance assessment at the end of each session.',
 3000, 15000, 'EGP', 7,
 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=1200&q=80',
 array['تدريب مخصص لاحتياج فريقك','أونلاين أو حضوري','مواد مكتوبة وفيديوهات','تطبيقات عملية مباشرة','اختبار قبول بنهاية الورشة']::text[],
 array['Custom training for your team needs','Online or onsite','Written materials and videos','Hands-on practical exercises','End-of-session assessment']::text[],
 array['مواد تدريبية مطبوعة ورقمية','تسجيل فيديو للورشة','شهادة اجتياز للمتدربين','جلسة متابعة بعد أسبوعين']::text[],
 array['Printed and digital materials','Session video recording','Completion certificates','Two-week follow-up session']::text[],
 20, true, false),

((select id from public.categories where slug = 'support-training'),
 'technical-docs', 'توثيق تقني', 'Technical Documentation',
 'أدلة استخدام، فيديوهات شرح، توثيق API — مكتبة كاملة تجيب أسئلة فريقك قبل أن يسأل.',
 'User guides, explainer videos, API docs — a library that answers your team questions before they ask.',
 'إنشاء مكتبة توثيق تقني احترافية لمنتجك أو نظامك الداخلي: أدلة مستخدم خطوة بخطوة بصور وشروحات، توثيق API بـ OpenAPI/Swagger مع أمثلة لكل endpoint، فيديوهات شرح قصيرة (3-5 دقائق) للميزات المعقدة، و FAQ ديناميكي. نستخدم منصات مثل GitBook، Notion، أو Docusaurus.',
 'A professional documentation library for your product or internal system: step-by-step illustrated user guides, OpenAPI/Swagger docs with examples per endpoint, short explainer videos (3-5 min) for complex features, and a dynamic FAQ. We use platforms like GitBook, Notion, or Docusaurus.',
 4000, 20000, 'EGP', 21,
 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1200&q=80',
 array['أدلة مستخدم مصوّرة خطوة بخطوة','توثيق API بـ OpenAPI/Swagger','فيديوهات شرح قصيرة','FAQ ديناميكي قابل للبحث','منصة GitBook / Notion / Docusaurus']::text[],
 array['Illustrated step-by-step user guides','OpenAPI/Swagger API docs','Short explainer videos','Searchable dynamic FAQ','GitBook / Notion / Docusaurus platform']::text[],
 array['مكتبة توثيق منشورة','فيديوهات شرح كاملة','ملفات مفتوحة قابلة للتحديث','صلاحيات تحرير لفريقك']::text[],
 array['Published documentation library','Complete explainer videos','Editable source files','Edit access for your team']::text[],
 30, true, false),

((select id from public.categories where slug = 'support-training'),
 'periodic-maintenance', 'صيانة دورية للمواقع والتطبيقات', 'Periodic Maintenance',
 'تحديثات أمنية، نسخ احتياطي، فحص أداء شهري، وإصلاحات صغيرة — كل شيء يبقى يعمل دون أن تشغل بالك.',
 'Security updates, backups, monthly performance audits, and small fixes — everything keeps running, hands-off.',
 'عقد صيانة شهري لموقعك أو تطبيقك: تحديث الأطر والمكتبات (WordPress، Laravel، Node packages)، تطبيق ترقيعات الأمان، نسخ احتياطي يومي مع تجربة استرجاع شهرية، فحص أداء شامل، إصلاحات صغيرة (حتى 5 ساعات شهرياً)، وتقرير صحة شامل. تنبيه فوري لأي خلل.',
 'Monthly maintenance contract for your site or app: framework and library updates (WordPress, Laravel, Node packages), security patches, daily backups with monthly restore drill, full performance audit, small fixes (up to 5 hours/month), and comprehensive health report. Real-time issue alerts.',
 2500, 12000, 'EGP', 30,
 'https://images.unsplash.com/photo-1581090464777-f3220bbe1b8b?auto=format&fit=crop&w=1200&q=80',
 array['تحديث الأطر والمكتبات شهرياً','ترقيعات أمنية فورية','نسخ احتياطي يومي + تجربة استرجاع','حتى 5 ساعات إصلاحات صغيرة','تقرير صحة شهري']::text[],
 array['Monthly framework and library updates','Immediate security patches','Daily backups plus monthly restore drill','Up to 5 hours of small fixes','Monthly health report']::text[],
 array['عقد صيانة شهري نشط','تقارير صحة شهرية','سجل التحديثات والإصلاحات','اجتماع مراجعة ربع سنوي']::text[],
 array['Active monthly maintenance contract','Monthly health reports','Update and fix log','Quarterly review meeting']::text[],
 40, true, false),

-- ═══ TESTING (8 services across 3 sub-categories) ════════════════════════════

-- ── Functional Testing ──
((select id from public.categories where slug = 'testing-functional'),
 'ui-testing', 'اختبار واجهة المستخدم', 'UI/UX Testing',
 'نختبر كل عنصر مرئي وكل مسار نقر — لنتأكد أن عميلك يكمل المهمة بسلاسة بدون عوائق.',
 'We test every visual element and click path — ensuring your customer completes tasks smoothly.',
 'فحص دقيق لكل واجهة في تطبيقك: محاذاة العناصر، ألوان، خطوط، تجاوب على مقاسات شاشة مختلفة (موبايل، تابلت، ديسكتوب)، حالات الفراغ والخطأ والتحميل، وإمكانية الوصول (Accessibility). نسلّمك تقريراً مع لقطات شاشة لكل مشكلة، أولوية، وخطوات إصلاح.',
 'Detailed inspection of every screen: element alignment, colors, typography, responsiveness across mobile/tablet/desktop, empty/error/loading states, and accessibility. You receive a report with screenshots per issue, priority, and remediation steps.',
 3000, 12000, 'EGP', 7,
 'https://images.unsplash.com/photo-1559028012-481c04fa702d?auto=format&fit=crop&w=1200&q=80',
 array['فحص محاذاة وألوان وخطوط','تجاوب على موبايل وتابلت وديسكتوب','حالات الفراغ والخطأ والتحميل','اختبار وصول WCAG','تقرير بلقطات شاشة وأولويات']::text[],
 array['Alignment, color, typography review','Responsive on mobile, tablet, desktop','Empty, error, loading states','WCAG accessibility checks','Screenshot report with priorities']::text[],
 array['تقرير شامل بكل المشاكل','لقطات شاشة لكل عيب','جدول أولويات إصلاح','إعادة اختبار بعد الإصلاح']::text[],
 array['Comprehensive findings report','Per-issue screenshots','Prioritized remediation list','Post-fix retesting']::text[],
 10, true, false),

((select id from public.categories where slug = 'testing-functional'),
 'business-logic-testing', 'اختبار الوظائف الأساسية', 'Business Logic Testing',
 'تنفيذ سيناريوهات الاستخدام من البداية للنهاية — تسجيل، شراء، استرداد، صلاحيات — نوثّق كل خطأ مهما صغر.',
 'End-to-end scenario execution — signup, purchase, refund, permissions — every bug documented.',
 'كتابة Test Cases شاملة لكل سيناريو رئيسي في نظامك (Happy Path + Edge Cases + Error Paths)، ثم تنفيذها يدوياً بدقة. نختبر تكاملاً بين الموديولات (مثلاً: شراء يخصم من المخزون ويرسل بريداً ويظهر في التقارير). كل bug يُسجّل في Jira أو نظامك مع خطوات إعادة الإنتاج.',
 'Complete Test Cases for every key scenario (Happy Path + Edge Cases + Error Paths), executed manually with care. We test integration across modules (e.g., a purchase deducts stock, sends an email, and appears in reports). Each bug logged in Jira or your system with reproduction steps.',
 5000, 20000, 'EGP', 14,
 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
 array['Test Cases شاملة لكل سيناريو','اختبار Happy Path + Edge Cases','اختبار تكامل بين الموديولات','تسجيل bugs في Jira أو نظامك','تقرير تغطية الاختبار']::text[],
 array['Comprehensive Test Cases per scenario','Happy Path + Edge Cases coverage','Cross-module integration testing','Bug logging in Jira or your tracker','Test coverage report']::text[],
 array['مكتبة Test Cases جاهزة','قائمة bugs مرتّبة بالأولوية','تقرير تغطية الاختبار','إعادة اختبار بعد الإصلاح']::text[],
 array['Test-case library','Prioritized bug list','Coverage report','Post-fix retesting']::text[],
 20, true, false),

((select id from public.categories where slug = 'testing-functional'),
 'security-testing', 'اختبار الأمان', 'Security Testing',
 'محاكاة هجمات حقيقية على تطبيقك (Penetration Testing) لاكتشاف الثغرات قبل المهاجمين.',
 'Simulating real attacks (penetration testing) to find vulnerabilities before attackers do.',
 'اختبار اختراق شامل لتطبيقك من منظور مهاجم خارجي: محاولات SQL Injection، XSS، CSRF، تجاوز المصادقة، رفع ملفات خبيثة، استغلال APIs، وكسر صلاحيات الأدوار. نستخدم أدوات احترافية (Burp Suite، OWASP ZAP) مع اختبار يدوي عميق. التقرير يشمل دليل استغلال لكل ثغرة وخطوات الإصلاح.',
 'Full penetration test from an external attacker perspective: SQL Injection, XSS, CSRF, auth bypass, malicious file upload, API abuse, and role permission breaks. We use professional tools (Burp Suite, OWASP ZAP) combined with deep manual testing. Report includes exploit walkthrough per vulnerability and remediation steps.',
 8000, 35000, 'EGP', 14,
 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&w=1200&q=80',
 array['اختبار اختراق آلي ويدوي','محاولات OWASP Top 10 كاملة','اختبار APIs والصلاحيات','دليل استغلال لكل ثغرة','إعادة اختبار بعد الإصلاح']::text[],
 array['Automated and manual penetration tests','Full OWASP Top 10 coverage','API and authorization testing','Exploit walkthrough per vulnerability','Post-fix retesting']::text[],
 array['تقرير اختراق مفصل','دليل استغلال لكل ثغرة','خطة إصلاح بأولويات','شهادة أمان بعد الإصلاح']::text[],
 array['Detailed pentest report','Exploit guide per vulnerability','Prioritized remediation plan','Post-fix security certificate']::text[],
 30, true, false),

-- ── Non-Functional Testing ──
((select id from public.categories where slug = 'testing-non-functional'),
 'performance-load-testing', 'اختبار الأداء والسرعة', 'Performance and Load Testing',
 'نختبر تطبيقك تحت ضغط آلاف المستخدمين المتزامنين — لنعرف نقطة الانهيار قبل أن يكتشفها العميل.',
 'Stress-test your app under thousands of concurrent users — find the breaking point before customers do.',
 'محاكاة أحمال حقيقية باستخدام JMeter، k6، أو Locust: 100، 500، 1000، 5000 مستخدم متزامن. نقيس زمن استجابة كل API، استخدام الـ CPU والذاكرة، والعنق الزجاجي (bottlenecks). نُحدّد عتبة الانهيار، نقترح تحسينات (caching، indexing، CDN، autoscaling)، ونعيد الاختبار للتأكد من التحسن.',
 'Realistic load simulation with JMeter, k6, or Locust: 100, 500, 1000, 5000 concurrent users. We measure per-API latency, CPU and memory usage, and bottlenecks. We identify the breaking point, recommend optimizations (caching, indexing, CDN, autoscaling), and re-test to verify improvement.',
 6000, 25000, 'EGP', 10,
 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
 array['محاكاة 100 إلى 5000 مستخدم متزامن','قياس زمن استجابة كل API','تحديد العنق الزجاجي (bottlenecks)','اقتراح تحسينات قابلة للتنفيذ','إعادة اختبار بعد التحسين']::text[],
 array['100 to 5000 concurrent user simulation','Per-API latency measurement','Bottleneck identification','Actionable optimization recommendations','Post-optimization retesting']::text[],
 array['تقرير أداء بالأرقام والرسوم','قائمة تحسينات بالأولوية','نتائج إعادة الاختبار','خطة المراقبة المستمرة']::text[],
 array['Performance report with charts','Prioritized optimization list','Retest results','Ongoing monitoring plan']::text[],
 10, true, false),

((select id from public.categories where slug = 'testing-non-functional'),
 'compatibility-testing', 'اختبار التوافق', 'Compatibility Testing',
 'نختبر على 30+ متصفح وجهاز — Chrome، Safari، iPhone، Samsung، Windows، Mac — لا أحد يتُرك خلف.',
 'Test across 30+ browsers and devices — Chrome, Safari, iPhone, Samsung, Windows, Mac — no one left behind.',
 'اختبار شامل لتطبيقك على مصفوفة كاملة من الأجهزة والمتصفحات: Chrome، Firefox، Safari، Edge بإصدارات حديثة وقديمة، على Windows، Mac، Linux، iOS (iPhone و iPad)، Android (Samsung، Xiaomi، Huawei). نستخدم BrowserStack و LambdaTest. تقرير بأي مشكلة على أي جهاز.',
 'Full app testing across a complete matrix of devices and browsers: Chrome, Firefox, Safari, Edge in current and older versions, on Windows, Mac, Linux, iOS (iPhone and iPad), Android (Samsung, Xiaomi, Huawei). Powered by BrowserStack and LambdaTest. Per-device report of every issue.',
 4000, 18000, 'EGP', 7,
 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&w=1200&q=80',
 array['30+ متصفح و OS مجتمعة','إصدارات حديثة وقديمة','iPhone و iPad و Android بأنواعها','منصات BrowserStack و LambdaTest','تقرير لكل جهاز/متصفح']::text[],
 array['30+ browser and OS combinations','Modern and legacy versions','iPhone, iPad, and Android variants','BrowserStack and LambdaTest platforms','Per-device/browser report']::text[],
 array['تقرير توافق مفصل','لقطات شاشة من كل جهاز','مصفوفة الدعم النهائية','توصيات تحسين التوافق']::text[],
 array['Detailed compatibility report','Per-device screenshots','Final support matrix','Compatibility recommendations']::text[],
 20, true, false),

((select id from public.categories where slug = 'testing-non-functional'),
 'usability-testing', 'اختبار قابلية الاستخدام', 'Usability Testing',
 'نراقب مستخدمين حقيقيين وهم يستخدمون تطبيقك — كل تردد، كل ضغطة خطأ، كل لحظة ارتباك.',
 'Watch real users navigate your app — every hesitation, every misclick, every moment of confusion.',
 'تنظيم جلسات اختبار قابلية استخدام مع 5-8 مستخدمين من جمهورك المستهدف. نضع لهم مهام واقعية ("اشترِ منتج"، "احجز موعد")، نسجّل الشاشة والصوت، ونلاحظ كل تردد ونقطة ارتباك. نحلّل الجلسات بتقنية "Think Aloud"، ونسلّمك تقريراً بالنتائج وفيديوهات قصيرة للحظات الحرجة.',
 'Usability test sessions with 5-8 users from your target audience. We give them realistic tasks ("buy a product", "book an appointment"), record screen and audio, and note every hesitation and confusion point. We analyze with "Think Aloud" methodology and deliver a report with findings plus short clips of critical moments.',
 5000, 22000, 'EGP', 14,
 'https://images.unsplash.com/photo-1559028012-481c04fa702d?auto=format&fit=crop&w=1200&q=80',
 array['5-8 مستخدمين من جمهورك','مهام واقعية محددة','تسجيل شاشة وصوت','تحليل Think Aloud','فيديوهات للحظات الحرجة']::text[],
 array['5-8 users from your audience','Realistic, defined tasks','Screen and audio recording','Think Aloud analysis','Clips of critical moments']::text[],
 array['تقرير قابلية استخدام مفصل','فيديوهات الجلسات','قائمة تحسينات بالأولوية','جلسة عرض ومناقشة']::text[],
 array['Detailed usability report','Session recordings','Prioritized improvements list','Presentation session']::text[],
 30, true, false),

-- ── Execution Method ──
((select id from public.categories where slug = 'testing-execution'),
 'manual-testing', 'اختبار يدوي', 'Manual Testing',
 'اختبار يدوي بعين بشرية للتفاصيل التي لا تكتشفها الآلة — تجربة، حدس، وذكاء سياقي.',
 'Hands-on testing with a human eye for nuance machines miss — experience, intuition, contextual smarts.',
 'فريق QA محترف يختبر تطبيقك يدوياً بمنهج Exploratory Testing + Test Cases منظّمة. اليد البشرية تكتشف ما لا تكتشفه الأتمتة: ارتباك مرئي، رسالة خطأ غير مفهومة، تردّد في تجربة المستخدم، ملاحظات مصممية. مناسب للمشاريع الجديدة، الإصدارات السنوية، أو التطبيقات ذات الواجهات المعقدة.',
 'A professional QA team testing manually with a mix of Exploratory Testing and structured Test Cases. Human hands catch what automation cannot: visual confusion, unclear error messages, UX hesitation, design notes. Ideal for new projects, annual releases, or apps with complex UIs.',
 4000, 18000, 'EGP', 10,
 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=1200&q=80',
 array['اختبار استكشافي + Test Cases','اكتشاف مشاكل UX دقيقة','ملاحظات مصممية ولغوية','يناسب الإصدارات الكبيرة','تقرير مفصل مع لقطات']::text[],
 array['Exploratory plus structured Test Cases','Subtle UX issue discovery','Design and copy feedback','Best for major releases','Detailed report with screenshots']::text[],
 array['تقرير اختبار شامل','قائمة bugs مرتّبة','ملاحظات تحسين تجربة المستخدم','إعادة اختبار بعد الإصلاح']::text[],
 array['Comprehensive test report','Sorted bug list','UX improvement notes','Post-fix retesting']::text[],
 10, true, false),

((select id from public.categories where slug = 'testing-execution'),
 'automated-testing', 'اختبار تلقائي', 'Automated Testing',
 'كتابة اختبارات Cypress، Playwright، أو Jest تعمل تلقائياً مع كل نسخة جديدة — جودة بدون انتظار.',
 'Cypress, Playwright, or Jest tests that run automatically on every build — quality at speed.',
 'بناء مكتبة اختبارات آلية لتطبيقك: Unit Tests للوحدات الحرجة (Jest)، Integration Tests للـ APIs (Supertest)، و End-to-End Tests للتدفقات الرئيسية (Cypress أو Playwright). دمج كامل مع CI/CD (GitHub Actions، GitLab CI) لتشغيل كل الاختبارات على كل Pull Request، ومنع نشر أي كود يكسر اختباراً.',
 'A complete automated test library: Unit Tests for critical units (Jest), Integration Tests for APIs (Supertest), and End-to-End Tests for major flows (Cypress or Playwright). Full CI/CD integration (GitHub Actions, GitLab CI) running every test on every Pull Request, blocking any code that breaks a test.',
 8000, 35000, 'EGP', 21,
 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=1200&q=80',
 array['Unit + Integration + E2E Tests','Cypress / Playwright / Jest','تكامل CI/CD كامل','تقرير تغطية الكود','تشغيل على كل Pull Request']::text[],
 array['Unit + Integration + E2E tests','Cypress / Playwright / Jest','Full CI/CD integration','Code-coverage report','Runs on every Pull Request']::text[],
 array['مكتبة اختبارات في الـ repo','إعدادات CI/CD جاهزة','تقرير تغطية الكود','تدريب للمطورين على التشغيل']::text[],
 array['Test library in the repo','Ready CI/CD setup','Code-coverage report','Developer training on usage']::text[],
 20, true, true)

on conflict (slug) do nothing;

-- ─── DONE ────────────────────────────────────────────────────────────────────
-- 7 root categories + 3 sub-categories + 37 services inserted (idempotent).
